"""IT fabric design targets (GPU / Storage / Arista / IB / Dell K8s)."""

from __future__ import annotations

GPU_MODEL = "NVIDIA B300"

GPU_COUNT = 5000

GPUS_PER_NODE = 8

GPU_NODE_COUNT = GPU_COUNT // GPUS_PER_NODE  # 625

GPU_NODES_PER_RACK = 16

GPU_RACK_COUNT = (GPU_NODE_COUNT + GPU_NODES_PER_RACK - 1) // GPU_NODES_PER_RACK  # 40

STORAGE_VENDOR = "IBM"

STORAGE_CAPACITY_PB = 100.0

STORAGE_CLUSTER_COUNT = 8

STORAGE_RACK_COUNT = 24

ARISTA_SPINE = 8

ARISTA_LEAF = 48

ARISTA_MODEL_SPINE = "Arista 7800R3"

ARISTA_MODEL_LEAF = "Arista 7060X6"

NVIDIA_IB_SWITCHES = 16

NVIDIA_IB_MODEL = "NVIDIA Quantum-2 QM9700"

DELL_K8S_NODES = 30

DELL_MODEL = "Dell PowerEdge XE9680"

K8S_CONTROL_PLANE = 3

K8S_WORKERS = DELL_K8S_NODES - K8S_CONTROL_PLANE

